# Author: Ajay Tak
# Date: 25-07-2022

import numpy as np

def co_actuator_model(M, B):

    """
    > M: The magnetic moment generated by magnetorquers
    > B: Earth's Magnetic field expressed in cubesat's body frame
    """

    M_cross = np.matrix([[    0, -M[2],  M[1]],
                         [ M[2],     0, -M[0]],
                         [-M[1],  M[0],     0]])
    multiply = np.dot(M_cross, B)
    T = np.array([multiply[0, 0], multiply[0, 1], multiply[0, 2]])

    return T